spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

#spring.kafka.bootstrap-servers=localhost:9092
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Kafka Consumer
#spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Consumer
spring.kafka.consumer.group-id=notification-service
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=web.minda.project.dto
spring.kafka.consumer.properties.spring.json.value.default.type=web.minda.project.dto.OrderEvent
spring.kafka.consumer.properties.spring.json.use.type.headers=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=deepakverma63427258@gmail.com
spring.mail.password=ohoo nepv ohbt qdxk

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


spring.datasource.name=jobportal
#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=jobportal;trustServerCertificate=true
#spring.datasource.username=remoteuser
#spring.datasource.password=remote@321
spring.datasource.url=${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=jobportal;trustServerCertificate=true}
spring.datasource.username=${DB_USERNAME:remoteuser}
spring.datasource.password=${DB_PASSWORD:remote@321}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update

server.ssl.enabled=true
server.ssl.key-alias=user-service
server.ssl.key-store=classpath:user-service.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=remote
server.port=8092
spring.main.allow-circular-references=true
java.opts=-Xmx20g
#server.servlet.context-path=/WebApplication
server.error.whitelabel.enabled=false
zpl.renderer.path=E:/Renderer/ZplRenderer.exespring.kafka.bootstrap-servers=localhost:9092
#
#spring.kafka.bootstrap-servers=localhost:9092
#
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer




# used for mail purpose in document approval system
spring.profiles.active=local 



qa.upload.path=D:/uploads/qa_docs/
server.address=0.0.0.0